// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/wmap.proto

package wmap_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeviceReport represents a simplified version of domain.Device for transport.
type DeviceReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           string                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Rssi          int32                  `protobuf:"varint,3,opt,name=rssi,proto3" json:"rssi,omitempty"`
	Ssid          string                 `protobuf:"bytes,4,opt,name=ssid,proto3" json:"ssid,omitempty"` // Beacon or Probed SSID
	ConnectedSsid string                 `protobuf:"bytes,5,opt,name=connected_ssid,json=connectedSsid,proto3" json:"connected_ssid,omitempty"`
	Latitude      float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	IsRandomized  bool                   `protobuf:"varint,8,opt,name=is_randomized,json=isRandomized,proto3" json:"is_randomized,omitempty"`
	Capabilities  []string               `protobuf:"bytes,9,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	IeTags        []int32                `protobuf:"varint,10,rep,packed,name=ie_tags,json=ieTags,proto3" json:"ie_tags,omitempty"`
	// Enhanced Fields
	Security  string `protobuf:"bytes,13,opt,name=security,proto3" json:"security,omitempty"`
	Standard  string `protobuf:"bytes,14,opt,name=standard,proto3" json:"standard,omitempty"`
	Model     string `protobuf:"bytes,15,opt,name=model,proto3" json:"model,omitempty"`
	Frequency int32  `protobuf:"varint,16,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// Analytics
	DataTransmitted int64 `protobuf:"varint,17,opt,name=data_transmitted,json=dataTransmitted,proto3" json:"data_transmitted,omitempty"`
	DataReceived    int64 `protobuf:"varint,18,opt,name=data_received,json=dataReceived,proto3" json:"data_received,omitempty"`
	PacketsCount    int32 `protobuf:"varint,19,opt,name=packets_count,json=packetsCount,proto3" json:"packets_count,omitempty"`
	RetryCount      int32 `protobuf:"varint,20,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	ChannelWidth    int32 `protobuf:"varint,21,opt,name=channel_width,json=channelWidth,proto3" json:"channel_width,omitempty"`
	// Type: "station" or "ap"
	Type          string `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     int64  `protobuf:"varint,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceReport) Reset() {
	*x = DeviceReport{}
	mi := &file_api_proto_wmap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceReport) ProtoMessage() {}

func (x *DeviceReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wmap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceReport.ProtoReflect.Descriptor instead.
func (*DeviceReport) Descriptor() ([]byte, []int) {
	return file_api_proto_wmap_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceReport) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *DeviceReport) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *DeviceReport) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *DeviceReport) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *DeviceReport) GetConnectedSsid() string {
	if x != nil {
		return x.ConnectedSsid
	}
	return ""
}

func (x *DeviceReport) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DeviceReport) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *DeviceReport) GetIsRandomized() bool {
	if x != nil {
		return x.IsRandomized
	}
	return false
}

func (x *DeviceReport) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *DeviceReport) GetIeTags() []int32 {
	if x != nil {
		return x.IeTags
	}
	return nil
}

func (x *DeviceReport) GetSecurity() string {
	if x != nil {
		return x.Security
	}
	return ""
}

func (x *DeviceReport) GetStandard() string {
	if x != nil {
		return x.Standard
	}
	return ""
}

func (x *DeviceReport) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceReport) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *DeviceReport) GetDataTransmitted() int64 {
	if x != nil {
		return x.DataTransmitted
	}
	return 0
}

func (x *DeviceReport) GetDataReceived() int64 {
	if x != nil {
		return x.DataReceived
	}
	return 0
}

func (x *DeviceReport) GetPacketsCount() int32 {
	if x != nil {
		return x.PacketsCount
	}
	return 0
}

func (x *DeviceReport) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *DeviceReport) GetChannelWidth() int32 {
	if x != nil {
		return x.ChannelWidth
	}
	return 0
}

func (x *DeviceReport) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DeviceReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReportSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DevicesProcessed int32                  `protobuf:"varint,1,opt,name=devices_processed,json=devicesProcessed,proto3" json:"devices_processed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportSummary) Reset() {
	*x = ReportSummary{}
	mi := &file_api_proto_wmap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSummary) ProtoMessage() {}

func (x *ReportSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wmap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSummary.ProtoReflect.Descriptor instead.
func (*ReportSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_wmap_proto_rawDescGZIP(), []int{1}
}

func (x *ReportSummary) GetDevicesProcessed() int32 {
	if x != nil {
		return x.DevicesProcessed
	}
	return 0
}

var File_api_proto_wmap_proto protoreflect.FileDescriptor

const file_api_proto_wmap_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/wmap.proto\x12\x04wmap\"\xfc\x04\n" +
	"\fDeviceReport\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\tR\x03mac\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x12\n" +
	"\x04rssi\x18\x03 \x01(\x05R\x04rssi\x12\x12\n" +
	"\x04ssid\x18\x04 \x01(\tR\x04ssid\x12%\n" +
	"\x0econnected_ssid\x18\x05 \x01(\tR\rconnectedSsid\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12#\n" +
	"\ris_randomized\x18\b \x01(\bR\fisRandomized\x12\"\n" +
	"\fcapabilities\x18\t \x03(\tR\fcapabilities\x12\x17\n" +
	"\aie_tags\x18\n" +
	" \x03(\x05R\x06ieTags\x12\x1a\n" +
	"\bsecurity\x18\r \x01(\tR\bsecurity\x12\x1a\n" +
	"\bstandard\x18\x0e \x01(\tR\bstandard\x12\x14\n" +
	"\x05model\x18\x0f \x01(\tR\x05model\x12\x1c\n" +
	"\tfrequency\x18\x10 \x01(\x05R\tfrequency\x12)\n" +
	"\x10data_transmitted\x18\x11 \x01(\x03R\x0fdataTransmitted\x12#\n" +
	"\rdata_received\x18\x12 \x01(\x03R\fdataReceived\x12#\n" +
	"\rpackets_count\x18\x13 \x01(\x05R\fpacketsCount\x12\x1f\n" +
	"\vretry_count\x18\x14 \x01(\x05R\n" +
	"retryCount\x12#\n" +
	"\rchannel_width\x18\x15 \x01(\x05R\fchannelWidth\x12\x12\n" +
	"\x04type\x18\v \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\f \x01(\x03R\ttimestamp\"<\n" +
	"\rReportSummary\x12+\n" +
	"\x11devices_processed\x18\x01 \x01(\x05R\x10devicesProcessed2I\n" +
	"\vWMapService\x12:\n" +
	"\rReportTraffic\x12\x12.wmap.DeviceReport\x1a\x13.wmap.ReportSummary(\x01B1Z/github.com/lcalzada-xor/wmap/api/grpc;wmap_grpcb\x06proto3"

var (
	file_api_proto_wmap_proto_rawDescOnce sync.Once
	file_api_proto_wmap_proto_rawDescData []byte
)

func file_api_proto_wmap_proto_rawDescGZIP() []byte {
	file_api_proto_wmap_proto_rawDescOnce.Do(func() {
		file_api_proto_wmap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_wmap_proto_rawDesc), len(file_api_proto_wmap_proto_rawDesc)))
	})
	return file_api_proto_wmap_proto_rawDescData
}

var file_api_proto_wmap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_wmap_proto_goTypes = []any{
	(*DeviceReport)(nil),  // 0: wmap.DeviceReport
	(*ReportSummary)(nil), // 1: wmap.ReportSummary
}
var file_api_proto_wmap_proto_depIdxs = []int32{
	0, // 0: wmap.WMapService.ReportTraffic:input_type -> wmap.DeviceReport
	1, // 1: wmap.WMapService.ReportTraffic:output_type -> wmap.ReportSummary
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_wmap_proto_init() }
func file_api_proto_wmap_proto_init() {
	if File_api_proto_wmap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_wmap_proto_rawDesc), len(file_api_proto_wmap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_wmap_proto_goTypes,
		DependencyIndexes: file_api_proto_wmap_proto_depIdxs,
		MessageInfos:      file_api_proto_wmap_proto_msgTypes,
	}.Build()
	File_api_proto_wmap_proto = out.File
	file_api_proto_wmap_proto_goTypes = nil
	file_api_proto_wmap_proto_depIdxs = nil
}
