// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: api/proto/wmap.proto

package wmap_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WMapService_ReportTraffic_FullMethodName = "/wmap.WMapService/ReportTraffic"
)

// WMapServiceClient is the client API for WMapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WMapService defines the distributed sensor reporting service.
type WMapServiceClient interface {
	// ReportTraffic streams captured device data from agent to server.
	ReportTraffic(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DeviceReport, ReportSummary], error)
}

type wMapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWMapServiceClient(cc grpc.ClientConnInterface) WMapServiceClient {
	return &wMapServiceClient{cc}
}

func (c *wMapServiceClient) ReportTraffic(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DeviceReport, ReportSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WMapService_ServiceDesc.Streams[0], WMapService_ReportTraffic_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeviceReport, ReportSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WMapService_ReportTrafficClient = grpc.ClientStreamingClient[DeviceReport, ReportSummary]

// WMapServiceServer is the server API for WMapService service.
// All implementations must embed UnimplementedWMapServiceServer
// for forward compatibility.
//
// WMapService defines the distributed sensor reporting service.
type WMapServiceServer interface {
	// ReportTraffic streams captured device data from agent to server.
	ReportTraffic(grpc.ClientStreamingServer[DeviceReport, ReportSummary]) error
	mustEmbedUnimplementedWMapServiceServer()
}

// UnimplementedWMapServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWMapServiceServer struct{}

func (UnimplementedWMapServiceServer) ReportTraffic(grpc.ClientStreamingServer[DeviceReport, ReportSummary]) error {
	return status.Error(codes.Unimplemented, "method ReportTraffic not implemented")
}
func (UnimplementedWMapServiceServer) mustEmbedUnimplementedWMapServiceServer() {}
func (UnimplementedWMapServiceServer) testEmbeddedByValue()                     {}

// UnsafeWMapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WMapServiceServer will
// result in compilation errors.
type UnsafeWMapServiceServer interface {
	mustEmbedUnimplementedWMapServiceServer()
}

func RegisterWMapServiceServer(s grpc.ServiceRegistrar, srv WMapServiceServer) {
	// If the following call panics, it indicates UnimplementedWMapServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WMapService_ServiceDesc, srv)
}

func _WMapService_ReportTraffic_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WMapServiceServer).ReportTraffic(&grpc.GenericServerStream[DeviceReport, ReportSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WMapService_ReportTrafficServer = grpc.ClientStreamingServer[DeviceReport, ReportSummary]

// WMapService_ServiceDesc is the grpc.ServiceDesc for WMapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WMapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wmap.WMapService",
	HandlerType: (*WMapServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportTraffic",
			Handler:       _WMapService_ReportTraffic_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/wmap.proto",
}
